=== BareBeaverBat/CSE5525_Structured_Data_Extraction/json_schemas/14_culinary_arts__recipes.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "dish_name": {
      "type": "string"
    },
    "ingredients": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "quantity": {
            "type": [
              "integer",
              "number"
            ]
          },
          "unit": {
            "type": "string"
          }
        },
        "required": [
          "name",
          "quantity"
        ],
        "additionalProperties": false
      }
    },
    "instructions_verbatim": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "cuisine": {
      "type": "string"
    },
    "dietary_restrictions": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "vegan",
          "vegetarian",
          "gluten-free",
          "dairy-free",
          "nut-free"
        ]
      }
    },
    "preparation_time_minutes": {
      "type": "integer"
    },
    "cooking_time_minutes": {
      "type": "integer"
    },
    "nutritional_information": {
      "type": "object",
      "properties": {
        "calories": {
          "type": "integer"
        },
        "protein_grams": {
          "type": "number"
        },
        "carbohydrates_grams": {
          "type": "number"
        },
        "fat_grams": {
          "type": "number"
        }
      },
      "additionalProperties": false
    }
  },
  "additionalProperties": false
}

=== BareBeaverBat/CSE5525_Structured_Data_Extraction/json_objects/gemini/14_culinary_arts__recipes__objs.json
[
    {
        "dish_name": "Rice Cakes",
        "ingredients": [
            {
                "name": "Rice Cakes",
                "quantity": 2,
                "unit": "cakes"
            }
        ],
        "dietary_restrictions": [
            "vegan",
            "vegetarian",
            "gluten-free",
            "dairy-free",
            "nut-free"
        ],
        "nutritional_information": {
            "calories": 70,
            "protein_grams": 1,
            "carbohydrates_grams": 15,
            "fat_grams": 0.5
        }
    },
    {
        "dish_name": "Pancakes",
        "ingredients": [
            {
                "name": "Pancake Mix",
                "quantity": 1,
                "unit": "cup"
            },
            {
                "name": "Water",
                "quantity": 0.75,
                "unit": "cup"
            }
        ],
        "cuisine": "American",
        "preparation_time_minutes": 10,
        "cooking_time_minutes": 20
    }
]
